export * from "./GeneroHero.jsx"
export * from "./FaraDescricion.jsx"
export * from "./LineaDeTrabajo.jsx"
export * from "./ProgramaEmpoderanos.jsx"
export * from "./Formacion.jsx"
export * from "./RecursosInformativos.jsx"
export * from "./EquipoDiciplinario.jsx"
export * from "./ApoyoFara.jsx"